name: Toyota Scraper Bot
on:
  # schedule:
  #   - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Scraper
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          TOYOTA_COOKIE: ${{ secrets.TOYOTA_COOKIE }}
        run: node scraper.js
